---
title: "Introduction | Spatial Covariates Workshop"
author: "Brian J. Smith"
date: "February 22, 2021"
output: 
  html_document:
    toc: true
    toc_float: true
css: ../my.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Welcome to the *Spatial Covariates Workshop*! This is a workshop for the [Space-use Ecology Lab](https://talavgar.com/) at [Utah State University](https://qcnr.usu.edu/wild/). This workshop was created in February 2021 to help give an overview of the diversity of approaches to downloading some common spatial covariates that we commonly use in our analyses. The workshop content was authored by [Brian J. Smith](mailto:brian.smith@usu.edu) (so now you know who to blame if it's terribly confusing! `r emo::ji("winking face")`).

This workshop will, of course, focus on the data we need for our analyses. But it is also focused on building the skills to download the remote data, efficiently, from wherever it may be housed. **Our focus will be on downloading data programmatically and reproducibly.** We will accomplish this by working from R, and this workshop and all of its associated materials are written almost entirely in R (with R Markdown).

## Software  

As I just mentioned, this workshop is mostly focused on using R. I will assume throughout that you have basic familiarity with R and RStudio. If you haven't updated your R and/or RStudio in a while, I'd recommend that you do that.

You can download R for your platform from [CRAN](https://cran.r-project.org/). You can download the RStudio IDE [here](https://rstudio.com/products/rstudio/download/).

Other software you will need are (1) utilities to build R packages from source and (2) GDAL. Unfortunately, installation of both will vary by operating system.

If you're on Windows:  

  1. Install Rtools. Go to this [link](https://cran.r-project.org/bin/windows/Rtools/) and follow all the directions on the page (including putting Rtools on the PATH).
  2. Install GDAL. This is easiest using the OSGeo4W installer, which you can download [here](https://trac.osgeo.org/osgeo4w/). The express install will give you the option of choosing QGIS, GDAL, and/or GRASS GIS. (I highly recommend QGIS and the GRASS tools, so if you feel like taking it for a test drive, go for it!). Decide what you want, but make sure you at least get GDAL.

If you're on Mac:  

  1. Install Xcode from the Mac App Store. I've read they might make you register (for free?) as a developer to download Xcode.
  2. Install GDAL. I found instructions for that [here](https://trac.osgeo.org/gdal/wiki/BuildingOnMac), but I've never done this myself. It looks like there's an option to download a binary, but Mac's package manager [Homebrew](https://brew.sh/) can also install it (`brew install gdal`). I've never used Homebrew, but if I had a Mac, that's the route I'd go. Package managers make installing technical software much easier, and this is likely not the last time you'll use it.

If you're on Linux:

  1. You can build R packages without extra tools! `r emo::ji("smiling face with sunglasses")`
  2. You probably know how to install GDAL better than I do! (but you can get [Homebrew](https://brew.sh/), too, if you don't like using bash to install packages).
  
## Workshop Website

All the materials for this workshop are available on GitHub. You can get the entire directory with all of the content from the workshop's GitHub repository (repo): https://github.com/bsmity13/spatial_covars/

You can also view the workshop materials as a website: https://bsmity13.github.io/spatial_covars/

Both the repo and the website link to each other. You'll probably want to make sure you bookmark one or the other to find your way back.

<span style = "font-size: 1.5em; font-weight: bold; align-text:center; color: green;">Happy coding!</span>

---

<a href = "../index.html" class = "workshop-home">Workshop Table of Contents</a>
